name: Try Actions GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          echo "Listing github.workspace: ${{ github.workspace }}"
          ls ${{ github.workspace }}
          echo "-- wibble.txt --"
          cat wibble.txt
          
      - name: Secret Stuff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPER_SECRET: ${{ secrets.MY_SECRET }}
          SUPER_SECRET2: ${{ secrets.MY_SECRET2 }}
          NEW_VAR: "51773"

        run: |
          echo "secret is $SUPER_SECRET"
          echo "secret2 is $SUPER_SECRET2"
          echo "GITHUB_TOKEN is $GITHUB_TOKEN"
          echo "NEW_VAR is $NEW_VAR"
          echo "USER is $USER"

      - name: My Test Step
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "oooh"
        
      - name: My Second Step
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "ahhh"
   
      - run: echo "🍏 This job's status is ${{ job.status }}."
