name: Try Actions GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          echo "Listing github.workspace: ${{ github.workspace }}"
          ls ${{ github.workspace }}
          echo "-- wibble.txt --"
          cat wibble.txt
          
      - name: Secret Stuff
        env:
          GITHUB_EVENT: ${{ github.event_name }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_SECRET2: ${{ secrets.MY_SECRET2 }}
          NEW_VAR: "51773"

        run: |
          echo "GITHUB_EVENT is $GITHUB_EVENT"
          echo "GITHUB_REPO is $GITHUB_REPO"
          echo "GITHUB_TOKEN is $GITHUB_TOKEN"
          echo "MY_SECRET is $MY_SECRET"
          echo "MY_SECRET2 is $MY_SECRET2"
          echo "NEW_VAR is $NEW_VAR"
          echo "USER is $USER"
          echo "PATH is $PATH"

   
      - run: echo "🍏 This job's status is ${{ job.status }}."
